s = 'AACATCAGTGGCTATTGGTCAAAACCCGTGTTCGTTAAAAGAGTCATGACGTAAGGTTTAGATATCTAGTTGTCAGCCTTAATGGTAACCATGACAAGTTCTCACAAACACATGCCATCGCGACTGAACCATGAAAGGGGCGGGGTCTATCCTGCGGGCTATTAATCCCGGTATTACGGATTAATATGTGATATGTGGACGAGGCATGCCGGTGGCTGCCAGTTCATCGAGAACGGGAATCCCCTGCGAGCGTACCATAGTGAAATACGCTACATCATCAGCACGCCTGAAGCTGACAATCAGAGAGCGCCCATATACACGACATTTTAATGCACTAAAGCAGCAAGCGTTCTGTTGCCATACGCTGTATAACCATATCTGTTGGCCCCGTCCATCTGACTACACTAAAGGCGCGGGTGCCCTACCTAGTTGGATCAAACCTACTCCACACTGGAGTAATTTAGCCCGGCTCTCGGCACCGGTTACTACTAGCTAAACAAGCTGAAGTAAGGACTGTCAATTTATCACCCAAAGATCACAACTGGAAAGCGCTAAGTATACCCCAAATGAATATAACGTCTGGTTCGTGTCTTTTACCCGACTGTAGCCTTTCATTTAGGAACGTGCTCATTAGAAATTAAACCCCATGCCATTTCCCACACGTGCGGTTCTCGATATGGCCGCTATCCACAAGAAGTTGCGTACGAGGGCAACGATGCCGTATTACCGGTTATCGCTAACAAGGCGCGGGGACTGTCGTAAAGACAGCAACCTAGTGGTGATAGAGGCCGCCACACAGCAGACCTTGTACGCACGAACTATT'

s = s.upper()

u = ''

pairs = {"A":"T", "T":"A", "C":"G", "G":"C"}

for nuc in s:
    if nuc in pairs:
        u = pairs[nuc] + u

print(u)


h = open("rosalind3ans.txt", "w+")
h.write(u)
h.close()
