acount = 0
ccount = 0
gcount = 0
tcount = 0
s = "GAAGTTCAACTACATTGCGATAACAATCTCTATTCAAGAAGCCGCTGAAGATGACATGGAGCGATTCGCTCAACTACTTAGACGCCGAAGCTAGGGACCCAATTGCCACATTGTAGTTGCTTTACGCTAGTGCCGGGACGTTGATCGATATTGCGCACAATAAAAACAACCCAGCCGTCAGATTACCCGTCCTTGTTAACCATAGAGCTAAGAGCTTGTAGAGGGCGTCGCTACAGCCGGGTAACCGCTTCTAATTTCTTACCCTAGCTAACTGGAGGCCTGGCCTTCACGCATGCCGGGAGGAGTGTGTTCCTTATCGGGTTTAAGCCTGAACCGGTCTCGAGCACCGTGTACACCAATACTTTTCAAACTCCATTGTACACTTGAATCCTCCGTTACCACGGGCCGAGGTAAAAGGCTCCATAGTGTTTGTGTTCCGCTTCTGAATCACTCGATTAATTAAAGTACTTTCTTACAAGGTTGCGGTGCCGCTTGCTGAAGCGGCTGGAGGTTTAGCGTGCTTCTCATGTCAAATCGTACATAAGGTTTCGCGGATTCCGATTTGATGCCACTAACTCAACTCTCTCCGTGAAAACTCTAGTGGGGCAACATGTGATACGCCCGAGTCATCAGTTGAATGTTGAGTGTTGATTTTCCAGCATTGTTTACAGGCAGTCCACCCTGAGCGGGTAGTTGACTAAGTGTGGCATGAGTATACTAAAGTCTAAAGTCCGTGTACACTTATCTGCCGTAGGGACCCCGGGCAGAGCGCCCGCTGGGATAGCACACTAGTTATGGTCGAAACGTCAGAGCGGGAGTGGCGATGCCTCCATAAGTCCGGTACGGTGCCAACATCCTTACAGCCAGTTGATCTACACGATGAGAACTAATGGTCATAACTTAGA"
s = s.upper()
for nuc in s:
    if nuc == "A":
        acount = acount + 1
    elif nuc == "C":
        ccount = ccount + 1
    elif nuc == "G":
        gcount = gcount + 1
    elif nuc == "T":
        tcount = tcount + 1

ans = str(acount) + " " + str(ccount) + " " + str(gcount) + " " + str(tcount)

h = open("rosalind1ans.txt", "w+")
h.write(ans)
h.close()
