t = 'TAAGTTTCTTAACCAATTTTTTAGAGAAAAGGTATCTACACTTCTGCGGGTTGAGCTCTTATTAGGTAGGGGTCGCTGCAATATAGTTATTCCTCATTCGCTGGCTCCATGTTATCAGGGAGGATTGCGGGAGCTCCGCGAACTTGCTAACTTTGGTACCATGTACCCATTACCGCTAAGCTCTGAGCCCTCAGCAACGAGAAGCATTATACTCTCCTATATTCCTCAGTGTGGGTTCGCATATAACGTTACCTAACGGAGCAAGATGTTACCGCTCGCCTACGAAGTTACACTATAAGGAACGCCCTTTCCCGCACATAGTTGGTGGCCTAAAGGGCCAAGGACGCCCCTGACAGGGTCAACGTAGAGAACAAAGTACGTTAAAATCAGGCTATACTGTACAAAAGACGTGGAGTCCGCCAGCCTATTGGTAGGCCATTTTCTAAATTGCCACCTGCCGCACCCGCATAACTTCATCCCACCAGCTCACACCGTATCGCCGCGAGCCAATGACTTACCCCGCGTCTGCAACTATTACAAGCTGGGCCATAGCCTGCTATGGCCTCGGATTCAAGAGATTCCGGCCCTCCTAACGCCCATGGAACGTGAGTTTCCATTAGTCCAGAGGCTTCCCCGACGACCCGATCGTTCAGATTCTTCCTAGTAACTGCATTTGGAGCTGGGTTTCCTTACGATGCGAGGATATCCCACACCTAACCCTACCGTGACGCCTACCGCCCTGTCAGCGTGTACGACTTTCGTCGCAGCCATATGCAGGACTATTTCGAAATCGGGGTTTACGGCGCGTGAATGGCGGACCAGTGCTGACAATCGTAGTTTGTCCCCACGTGAGTGTATCACCTCGCGACTCATAGCTAATTCCCCCCCACTTTGCAAATGCTATGGAGAGCAGCCACTGGGCTCTTGTGAAACTACGATTAGACGCAAGCGT'
u = ''

t = t.upper()

othernucs = ["A", "G", "C"]
for nuc in t:
    if nuc == "T":
        u = u + "U"
    elif nuc in othernucs:
        u = u + nuc

print(u)

h = open("rosalind2ans.txt", "w+")
h.write(u)
h.close()
