s = "GCAATGTTGCAATGTTAACAATGTTACAATGTTCCAGTCAATGTTCAATGTTCAATGTTCAATGTTGACAGCAATGTTACAATGTTACTATCTCCAATGTTAACAATGTTCCAATGTTAGCCAGCGCTATTCGAGCGGATCAATGTTTCAATGTTCGCCAATGTTTCCAATGTTCAATGTTCCAACACGCAATGTTGTCAATGTTGCCCTGTCAATGTTAATCCAATGTTCTCTAGGCAATGTTCCCAACGAAGCAATGTTCAATGTTGATGTCACAATGTTAACCCAATGTTTCCAATGTTCAATGTTATAACGTCAATGTTCAACTCAATGTTTAGCCCAATGTTCAATGTTATCAATGTTCAATGTTAACGCAATGTTTACAATGTTTACAATGTTGCCGGCAATGTTCGTCAATGTTGAGCAATGTTCAATGTTACCAATGTTCCAATGTTATCCAATGTTAAGCAATGTTTTACAATGTTTCAATGTTCAATGTTAGGTACAATGTTCAATGTTCGAAGCAATGTTATCCCAATGTTGGCAATGTTATGACCAATGTTCATGCAATGTTACAATGTTACGTGCAACAATGTTCAATGTTCAATGTTCCCAATGTTGATCTATGGCAATGTTCAATGTTCCAATGTTCAATGTTGCAATGTTCTTCTCAATGTTAAACAATGTTACGTCAATGTTCAATGTTACAATGTTCAATGTTCCAATGTTCAATGTTCCTGCAATGTTAGCAATGTTCATCAATGTTCAATGTTGTAAGAGGCAATGTTGCAATGTTCAATGTTCAATGTTCAATGTTGCAATGTT"
t = "CAATGTTCA"

listfrag = []
for x in range(0,len(s)):
    fragment = s[x:x+len(t)]
    if t == fragment:
        listfrag.append(x+1)

print(listfrag)

stringfrag = ""
for x in listfrag:
    x = str(x)
    if not stringfrag:
        stringfrag = x
    else:
        stringfrag = stringfrag + " " + x

print(stringfrag)

h = open("rosalind9ans.txt", "w+")
h.write(stringfrag)
h.close()
